---
- hosts: mywebservers
  become: yes
  tasks:
- name: i want to  java install ansible ubuntu nodes
  apt:
    name: "{{myjavapackkforubuntu}}"
    state: present
  when: ansible_os_family =="Debian"

- name: i want to  java install ansible RedHat nodes
  yum:
    name: j"{{myjavapackkforredhat}}"
    state: present
  when: ansible_os_family =="RedHat"