---
- hosts: mywebservers
  become: yes
  tasks:
  - name: I want to insatall tree
    apt:
      name: tree
      state: present
    when: ansible_os_family =="Debian"

  - name: i want to start webserver on ansible ubuntu nodes
    service:
      name: "{{mywebpackforubuntu}}"
      state: started
    when: ansible_os_family =="Debian"

  - name: i want to install webserver on ansible RedHat nodes
    yum:
      name: "{{mywebpackforredhat}}"
      state: present
    when: ansible_os_family =="RedHat"