---
- hosts: all
  become: yes
  tasks:
  - name: i want to insatll webserver on ansible ubuntu nodes
    apt:
      name: apache2
      state: present
    when: ansible_os_family =="Debian"

  - name: i want to start webserver on ansible ubuntu nodes
    service:
      name: apache2
      state: present
    when: ansible_os_family =="Debian"